//read alll my code if i search with if i seatrch 0000 id this admin id show all data wich is work properly //if i search with {
    "first_name": "admin",
    "employee_id": "0000"
} //show only admin data wich is correct if search with secific 1230 id which in another admin show the data which status are approved like this {
    "empid": "2130"
    
} and responce is {
    "id": "2130",
    "message": "Successfull Found",
    "status": "success",
    "response": [
        {
            "id": "3",
            "employeeid": "21463",
            "assign_id": "39",
            "count": "2.00",
            "status": "Approved",
            "start": "2021-12-07",
            "half_start": null,
            "half_end": null,
            "end": "2021-12-08",
            "approver": "2130",
            "created_at": "2021-03-11 12:10:14",
            "updated_at": "2021-12-08 05:45:28",
            "reason": "test",
            "reject_reason": "",
            "rejoin": null,
            "first_name": "Sandeepa",
            "last_name": "Datta",
            "email": "sdatta@jcboe.org",
            "location": "78",
            "department": "4",
            "type": "Personal day",
            "is_active": "1",
            "is_deleted": "0",
            "color": "#00cccc",
            "isdeleted": "0",
            "appid": "1",
            "locationname": "Innovation",
            "leave_count": "5",
            "Leavestart": "12-07-2021",
            "Leaveend": "12-08-2021"
        },
        {
            "id": "3",
            "employeeid": "21463",
            "assign_id": "39",
            "count": "2.00",
            "status": "Approved",
            "start": "2021-12-06",
            "half_start": null,
            "half_end": null,
            "end": "2021-12-07",
            "approver": "2130",
            "created_at": "2021-03-11 12:10:14",
            "updated_at": "0000-00-00 00:00:00",
            "reason": "test",
            "reject_reason": null,
            "rejoin": null,
            "first_name": "Sandeepa",
            "last_name": "Datta",
            "email": "sdatta@jcboe.org",
            "location": "78",
            "department": "4",
            "type": "Personal day",
            "is_active": "1",
            "is_deleted": "0",
            "color": "#00cccc",
            "isdeleted": "0",
            "appid": "4",
            "locationname": "Innovation",
            "leave_count": "5",
            "Leavestart": "12-06-2021",
            "Leaveend": "12-07-2021"
        },
        {
            "id": "4",
            "employeeid": "21463",
            "assign_id": "40",
            "count": "1.00",
            "status": "Approved",
            "start": "2021-12-10",
            "half_start": null,
            "half_end": null,
            "end": "2021-12-10",
            "approver": "2130",
            "created_at": "2021-03-11 12:10:14",
            "updated_at": "0000-00-00 00:00:00",
            "reason": "personal",
            "reject_reason": null,
            "rejoin": null,
            "first_name": "Sandeepa",
            "last_name": "Datta",
            "email": "sdatta@jcboe.org",
            "location": "78",
            "department": "4",
            "type": "Personal Development",
            "is_active": "1",
            "is_deleted": "0",
            "color": "#c390dd",
            "isdeleted": "0",
            "appid": "7",
            "locationname": "Innovation",
            "leave_count": "2",
            "Leavestart": "12-10-2021",
            "Leaveend": "12-10-2021"
        },
        {
            "id": "1",
            "employeeid": "21463",
            "assign_id": "37",
            "count": "1.00",
            "status": "Rejected",
            "start": "2021-12-09",
            "half_start": null,
            "half_end": null,
            "end": "2021-12-09",
            "approver": "2130",
            "created_at": "2021-03-11 12:10:14",
            "updated_at": "2021-12-08 05:47:44",
            "reason": "personal",
            "reject_reason": "rejected",
            "rejoin": null,
            "first_name": "Sandeepa",
            "last_name": "Datta",
            "email": "sdatta@jcboe.org",
            "location": "78",
            "department": "4",
            "type": "Vacation day",
            "is_active": "1",
            "is_deleted": "0",
            "color": "#00adef",
            "isdeleted": "0",
            "appid": "33",
            "locationname": "Innovation",
            "leave_count": "5",
            "Leavestart": "12-09-2021",
            "Leaveend": "12-09-2021"
        },
        {
            "id": "1",
            "employeeid": "21463",
            "assign_id": "37",
            "count": "2.00",
            "status": "Approved",
            "start": "2021-12-09",
            "half_start": null,
            "half_end": null,
            "end": "2021-12-10",
            "approver": "2130",
            "created_at": "2021-03-11 12:10:14",
            "updated_at": "2021-12-08 06:32:33",
            "reason": "Going out with family to india",
            "reject_reason": "",
            "rejoin": null,
            "first_name": "Sandeepa",
            "last_name": "Datta",
            "email": "sdatta@jcboe.org",
            "location": "78",
            "department": "4",
            "type": "Vacation day",
            "is_active": "1",
            "is_deleted": "0",
            "color": "#00adef",
            "isdeleted": "0",
            "appid": "34",
            "locationname": "Innovation",
            "leave_count": "5",
            "Leavestart": "12-09-2021",
            "Leaveend": "12-10-2021"
        },
        {
            "id": "2",
            "employeeid": "21463",
            "assign_id": "38",
            "count": "0.50",
            "status": "Approved",
            "start": "2022-03-30",
            "half_start": "2022-03-30",
            "half_end": "2022-03-30",
            "end": "2022-03-30",
            "approver": "2130",
            "created_at": "2021-03-11 12:10:14",
            "updated_at": "2022-03-28 04:05:57",
            "reason": "fever",
            "reject_reason": "",
            "rejoin": null,
            "first_name": "Sandeepa",
            "last_name": "Datta",
            "email": "sdatta@jcboe.org",
            "location": "78",
            "department": "4",
            "type": "Sick day",
            "is_active": "1",
            "is_deleted": "0",
            "color": "#eeabab",
            "isdeleted": "0",
            "appid": "67",
            "locationname": "Innovation",
            "leave_count": "3",
            "Leavestart": "03-30-2022",
            "Leaveend": "03-30-2022"
        }
    ],
    "pagination": {
        "totalCount": 6,
        "totalPage": 1
    }
} //so fix the part only where need to change